/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "LED_2.h"
#include "LED_2_aliases.h"
#include "LED_3.h"
#include "LED_3_aliases.h"
#include "LED_4.h"
#include "LED_4_aliases.h"
#include "I2C_1.h"
#include "I2C_1_I2C.h"
#include "I2C_1_PINS.h"
#include "I2C_1_I2C_PVT.h"
#include "I2C_1_PVT.h"
#include "I2C_1_BOOT.h"
#include "I2C_1_SCBCLK.h"
#include "I2C_1_sda.h"
#include "I2C_1_sda_aliases.h"
#include "I2C_1_scl.h"
#include "I2C_1_scl_aliases.h"
#include "I2C_1_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

