# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Henry Alberto\Desktop\Test_Robot\Test_LED.cydsn\Test_LED.cyprj
# Date: Tue, 03 Jan 2017 19:34:11 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\Henry Alberto\Desktop\Test_Robot\Test_LED.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Henry Alberto\Desktop\Test_Robot\Test_LED.cydsn\Test_LED.cyprj
# Date: Tue, 03 Jan 2017 19:34:06 GMT
