/*******************************************************************************
* File Name: SENSOR_PWM.c
* Version 2.40
*
* Description:
*  This file provides the source code to the API for the Sequencing Successive
*  Approximation ADC Component Component.
*
* Note:
*
********************************************************************************
* Copyright 2008-2015, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "SENSOR_PWM.h"


/***************************************
* Global data allocation
***************************************/
uint8 SENSOR_PWM_initVar = 0u;
volatile int16 SENSOR_PWM_offset[SENSOR_PWM_TOTAL_CHANNELS_NUM];
volatile int32 SENSOR_PWM_countsPer10Volt[SENSOR_PWM_TOTAL_CHANNELS_NUM];   /* Gain compensation */


/***************************************
* Local data allocation
***************************************/
/* Channels configuration generated by customiser */
static const uint32 CYCODE SENSOR_PWM_channelsConfig[] = { 0x00000000u };


/*******************************************************************************
* Function Name: SENSOR_PWM_Start
********************************************************************************
*
* Summary:
*  Performs all required initialization for this component
*  and enables the power. The power will be set to the appropriate
*  power based on the clock frequency.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
* Global variables:
*  The SENSOR_PWM_initVar variable is used to indicate when/if initial
*  configuration of this component has happened. The variable is initialized to
*  zero and set to 1 the first time ADC_Start() is called. This allows for
*  component Re-Start without re-initialization in all subsequent calls to the
*  SENSOR_PWM_Start() routine.
*  If re-initialization of the component is required the variable should be set
*  to zero before call of SENSOR_PWM_Start() routine, or the user may call
*  SENSOR_PWM_Init() and SENSOR_PWM_Enable() as done in the
*  SENSOR_PWM_Start() routine.
*
*******************************************************************************/
void SENSOR_PWM_Start(void)
{
    /* If not Initialized then initialize all required hardware and software */
    if(SENSOR_PWM_initVar == 0u)
    {
        SENSOR_PWM_Init();
        SENSOR_PWM_initVar = 1u;
    }
    SENSOR_PWM_Enable();
}


/*******************************************************************************
* Function Name: SENSOR_PWM_Init
********************************************************************************
*
* Summary:
*  Initialize component's parameters to the parameters set by user in the
*  customizer of the component placed onto schematic. Usually called in
*  SENSOR_PWM_Start().
*
* Parameters:
*  None.
*
* Return:
*  None.
*
* Global variables:
*  The SENSOR_PWM_offset variable is initialized.
*
*******************************************************************************/
void SENSOR_PWM_Init(void)
{
    uint32 chNum;
    uint32 tmpRegVal;
    int32 counts;

    #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 1u)
        static const uint8 CYCODE SENSOR_PWM_InputsPlacement[] =
        {
            (uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_0_PORT << 4u) |
            (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_0_PIN
            ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_1_PORT << 4u) |
             (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_1_PIN
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 2u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_2_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_2_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 2u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 3u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_3_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_3_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 3u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 4u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_4_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_4_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 4u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 5u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_5_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_5_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 5u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 6u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_6_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_6_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 6u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 7u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_7_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_7_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 7u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 8u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_8_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_8_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 8u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 9u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_9_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_9_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 9u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 10u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_10_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_10_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 10u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 11u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_11_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_11_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 11u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 12u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_12_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_12_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 12u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 13u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_13_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_13_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 13u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 14u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_14_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_14_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 14u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 15u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_15_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_15_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 15u */
            #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 16u)
                ,(uint8)(SENSOR_PWM_cy_psoc4_sarmux_8__CH_16_PORT << 4u) |
                 (uint8)SENSOR_PWM_cy_psoc4_sarmux_8__CH_16_PIN
            #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 16u */
        };
    #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 1u */

    #if(SENSOR_PWM_IRQ_REMOVE == 0u)
        /* Start and set interrupt vector */
        CyIntSetPriority(SENSOR_PWM_INTC_NUMBER, SENSOR_PWM_INTC_PRIOR_NUMBER);
        (void)CyIntSetVector(SENSOR_PWM_INTC_NUMBER, &SENSOR_PWM_ISR);
    #endif   /* End SENSOR_PWM_IRQ_REMOVE */

    /* Init SAR and MUX registers */
    SENSOR_PWM_SAR_CHAN_EN_REG = SENSOR_PWM_DEFAULT_EN_CHANNELS;
    SENSOR_PWM_SAR_CTRL_REG |= SENSOR_PWM_DEFAULT_CTRL_REG_CFG | 
        /* Enable the SAR internal pump when global pump is enabled */
        (((SENSOR_PWM_PUMP_CTRL_REG & SENSOR_PWM_PUMP_CTRL_ENABLED) != 0u) ? 
        SENSOR_PWM_BOOSTPUMP_EN : 0u);
    SENSOR_PWM_SAR_SAMPLE_CTRL_REG = SENSOR_PWM_DEFAULT_SAMPLE_CTRL_REG_CFG;
    SENSOR_PWM_SAR_RANGE_THRES_REG = SENSOR_PWM_DEFAULT_RANGE_THRES_REG_CFG;
    SENSOR_PWM_SAR_RANGE_COND_REG  = SENSOR_PWM_COMPARE_MODE;
    SENSOR_PWM_SAR_SAMPLE_TIME01_REG = SENSOR_PWM_DEFAULT_SAMPLE_TIME01_REG_CFG;
    SENSOR_PWM_SAR_SAMPLE_TIME23_REG = SENSOR_PWM_DEFAULT_SAMPLE_TIME23_REG_CFG;
    
    /* Connect Vm to VSSA when even one channel is single-ended or multiple channels configured */
    #if(SENSOR_PWM_DEFAULT_MUX_SWITCH0 != 0u)
        SENSOR_PWM_MUX_SWITCH0_REG |= SENSOR_PWM_DEFAULT_MUX_SWITCH0;
        /* Set MUX_HW_CTRL_VSSA in MUX_SWITCH_HW_CTRL when multiple channels enabled */
        #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 1u)
            SENSOR_PWM_MUX_SWITCH_HW_CTRL_REG |= SENSOR_PWM_DEFAULT_MUX_SWITCH0;
        #endif /* SENSOR_PWM_TOTAL_CHANNELS_NUM > 1u */
    #endif /*SENSOR_PWM_CHANNELS_MODE !=0 */

    SENSOR_PWM_SAR_SATURATE_INTR_MASK_REG = 0u;
    SENSOR_PWM_SAR_RANGE_INTR_MASK_REG = 0u;
    SENSOR_PWM_SAR_INTR_MASK_REG = SENSOR_PWM_SAR_INTR_MASK;

    #if(SENSOR_PWM_CY_SAR_IP_VER == SENSOR_PWM_CY_SAR_IP_VER0)
        SENSOR_PWM_ANA_TRIM_REG = SENSOR_PWM_TRIM_COEF;
    #endif /* (SENSOR_PWM_CY_SAR_IP_VER == SENSOR_PWM_CY_SAR_IP_VER0) */

    /* Read and modify default configuration based on characterization */
    tmpRegVal = SENSOR_PWM_SAR_DFT_CTRL_REG;
    tmpRegVal &= (uint32)~SENSOR_PWM_DCEN;
    
    #if(SENSOR_PWM_CY_SAR_IP_VER == SENSOR_PWM_CY_SAR_IP_VER0)
        #if(SENSOR_PWM_NOMINAL_CLOCK_FREQ > (SENSOR_PWM_MAX_FREQUENCY / 2))
            tmpRegVal |= SENSOR_PWM_SEL_CSEL_DFT_CHAR;
        #else  /* clock speed < 9 Mhz */
            tmpRegVal |= SENSOR_PWM_DLY_INC;
        #endif /* clock speed > 9 Mhz */
    #else
        #if ((SENSOR_PWM_DEFAULT_VREF_SEL == SENSOR_PWM__INTERNAL1024) || \
             (SENSOR_PWM_DEFAULT_VREF_SEL == SENSOR_PWM__INTERNALVREF))
            tmpRegVal |= SENSOR_PWM_DLY_INC;
        #else
            tmpRegVal |= SENSOR_PWM_DCEN;
            tmpRegVal &= (uint32)~SENSOR_PWM_DLY_INC;
        #endif /* ((SENSOR_PWM_DEFAULT_VREF_SEL == SENSOR_PWM__INTERNAL1024) || \
                   (SENSOR_PWM_DEFAULT_VREF_SEL == SENSOR_PWM__INTERNALVREF)) */
    #endif /* (SENSOR_PWM_CY_SAR_IP_VER == SENSOR_PWM_CY_SAR_IP_VER0) */
    
    SENSOR_PWM_SAR_DFT_CTRL_REG = tmpRegVal;

    #if(SENSOR_PWM_MAX_RESOLUTION != SENSOR_PWM_RESOLUTION_12)
        SENSOR_PWM_WOUNDING_REG = SENSOR_PWM_ALT_WOUNDING;
    #endif /* SENSOR_PWM_MAX_RESOLUTION != SENSOR_PWM_RESOLUTION_12 */

    for(chNum = 0u; chNum < SENSOR_PWM_TOTAL_CHANNELS_NUM; chNum++)
    {
        tmpRegVal = (SENSOR_PWM_channelsConfig[chNum] & SENSOR_PWM_CHANNEL_CONFIG_MASK);
        #if(SENSOR_PWM_TOTAL_CHANNELS_NUM > 1u)
            tmpRegVal |= SENSOR_PWM_InputsPlacement[chNum];
        #endif /* End SENSOR_PWM_TOTAL_CHANNELS_NUM > 1u */
        
        
        /* When the part is limited to 10-bit then the SUB_RESOLUTION bit
        *  will be ignored and the RESOLUTION bit selects between 10-bit
        *  (0) and 8-bit (1) resolution.
        */
        #if((SENSOR_PWM_MAX_RESOLUTION != SENSOR_PWM_RESOLUTION_12) && \
            (SENSOR_PWM_ALT_WOUNDING == SENSOR_PWM_WOUNDING_10BIT))
            tmpRegVal &= (uint32)(~SENSOR_PWM_ALT_RESOLUTION_ON);
        #endif /* SENSOR_PWM_MAX_RESOLUTION != SENSOR_PWM_RESOLUTION_12 */

        #if(SENSOR_PWM_INJ_CHANNEL_ENABLED)
        if(chNum < SENSOR_PWM_SEQUENCED_CHANNELS_NUM)
        #endif /* SENSOR_PWM_INJ_CHANNEL_ENABLED */
        {
            CY_SET_REG32((reg32 *)(SENSOR_PWM_SAR_CHAN_CONFIG_IND + (uint32)(chNum << 2)), tmpRegVal);

            if((SENSOR_PWM_channelsConfig[chNum] & SENSOR_PWM_IS_SATURATE_EN_MASK) != 0u)
            {
                SENSOR_PWM_SAR_SATURATE_INTR_MASK_REG |= (uint16)((uint16)1 << chNum);
            }

            if((SENSOR_PWM_channelsConfig[chNum] & SENSOR_PWM_IS_RANGE_CTRL_EN_MASK) != 0u)
            {
                SENSOR_PWM_SAR_RANGE_INTR_MASK_REG |= (uint16)((uint16)1 << chNum);
            }
        }
        #if(SENSOR_PWM_INJ_CHANNEL_ENABLED)
            else
            {
                CY_SET_REG32(SENSOR_PWM_SAR_INJ_CHAN_CONFIG_PTR, tmpRegVal | SENSOR_PWM_INJ_TAILGATING);

                if((SENSOR_PWM_channelsConfig[chNum] & SENSOR_PWM_IS_SATURATE_EN_MASK) != 0u)
                {
                    SENSOR_PWM_SAR_INTR_MASK_REG |= SENSOR_PWM_INJ_SATURATE_MASK;
                }

                if((SENSOR_PWM_channelsConfig[chNum] & SENSOR_PWM_IS_RANGE_CTRL_EN_MASK) != 0u)
                {
                    SENSOR_PWM_SAR_INTR_MASK_REG |= SENSOR_PWM_INJ_RANGE_MASK;
                }
            }
        #endif /* SENSOR_PWM_INJ_CHANNEL_ENABLED */

        if((SENSOR_PWM_channelsConfig[chNum] & SENSOR_PWM_ALT_RESOLUTION_ON) != 0u)
        {
               counts = (int32)SENSOR_PWM_DEFAULT_MAX_WRK_ALT;
        }
        else
        {
               counts = (int32)SENSOR_PWM_SAR_WRK_MAX_12BIT;
        }

        if((SENSOR_PWM_channelsConfig[chNum] & SENSOR_PWM_DIFFERENTIAL_EN) == 0u)
        {
            #if((SENSOR_PWM_DEFAULT_SE_RESULT_FORMAT_SEL == SENSOR_PWM__FSIGNED) && \
                (SENSOR_PWM_DEFAULT_NEG_INPUT_SEL == SENSOR_PWM__VREF))
                /* Set offset to the minus half scale to convert results to unsigned format */
                SENSOR_PWM_offset[chNum] = (int16)(counts / -2);
            #else
                SENSOR_PWM_offset[chNum] = 0;
            #endif /* end DEFAULT_SE_RESULT_FORMAT_SEL == SENSOR_PWM__FSIGNED */
        }
        else    /* Differential channel */
        {
            #if(SENSOR_PWM_DEFAULT_DIFF_RESULT_FORMAT_SEL == SENSOR_PWM__FUNSIGNED)
                /* Set offset to the half scale to convert results to signed format */
                SENSOR_PWM_offset[chNum] = (int16)(counts / 2);
            #else
                SENSOR_PWM_offset[chNum] = 0;
            #endif /* end SENSOR_PWM_DEFAULT_DIFF_RESULT_FORMAT_SEL == SENSOR_PWM__FUNSIGNED */
        }
        /* Calculate gain in counts per 10 volts with rounding */
        SENSOR_PWM_countsPer10Volt[chNum] = (int16)(((counts * SENSOR_PWM_10MV_COUNTS) +
                            SENSOR_PWM_DEFAULT_VREF_MV_VALUE) / (SENSOR_PWM_DEFAULT_VREF_MV_VALUE * 2));
    }
}

/*******************************************************************************
* Function Name: ADC_SAR_1_Enable
********************************************************************************
*
* Summary:
*  Enables the clock and analog power for SAR ADC.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void SENSOR_PWM_Enable(void)
{
    if (0u == (SENSOR_PWM_SAR_CTRL_REG & SENSOR_PWM_ENABLE))
    {
        #if(SENSOR_PWM_CY_SAR_IP_VER != SENSOR_PWM_CY_SAR_IP_VER0)

            while (0u != (SENSOR_PWM_SAR_STATUS_REG & SENSOR_PWM_STATUS_BUSY))
            {
                /* wait for SAR to go idle to avoid deadlock */
            }
        #endif /* (SENSOR_PWM_CY_SAR_IP_VER != SENSOR_PWM_CY_SAR_IP_VER0) */
        
        SENSOR_PWM_SAR_CTRL_REG |= SENSOR_PWM_ENABLE;
        
        /* The block is ready to use 10 us after the enable signal is set high. */
        CyDelayUs(SENSOR_PWM_10US_DELAY);         
    }
}


/*******************************************************************************
* Function Name: SENSOR_PWM_Stop
********************************************************************************
*
* Summary:
*  This function stops ADC conversions and puts the ADC into its lowest power
*  mode.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void SENSOR_PWM_Stop(void)
{
    SENSOR_PWM_SAR_CTRL_REG &= (uint32)~SENSOR_PWM_ENABLE;
}


/*******************************************************************************
* Function Name: SENSOR_PWM_StartConvert
********************************************************************************
*
* Summary:
*  Description:
*  For free running mode, this API starts the conversion process and it
*  runs continuously.
*
*  In a triggered mode, this routine triggers every conversion by
*  writing into the FW_TRIGGER bit in SAR_START_CTRL reg. In triggered mode,
*  every conversion has to start by this API.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void SENSOR_PWM_StartConvert(void)
{
    #if(SENSOR_PWM_DEFAULT_SAMPLE_MODE_SEL == SENSOR_PWM__FREERUNNING)
        SENSOR_PWM_SAR_SAMPLE_CTRL_REG |= SENSOR_PWM_CONTINUOUS_EN;
    #else /* Firmware trigger */
        SENSOR_PWM_SAR_START_CTRL_REG = SENSOR_PWM_FW_TRIGGER;
    #endif /* End SENSOR_PWM_DEFAULT_SAMPLE_MODE == SENSOR_PWM__FREERUNNING */

}


/*******************************************************************************
* Function Name: SENSOR_PWM_StopConvert
********************************************************************************
*
* Summary:
*  Forces the ADC to stop all conversions.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void SENSOR_PWM_StopConvert(void)
{
    #if(SENSOR_PWM_DEFAULT_SAMPLE_MODE_SEL == SENSOR_PWM__FREERUNNING)
        SENSOR_PWM_SAR_SAMPLE_CTRL_REG &= (uint32)(~SENSOR_PWM_CONTINUOUS_EN);
    #endif /* SENSOR_PWM_DEFAULT_SAMPLE_MODE == SENSOR_PWM__FREERUNNING */
}


/*******************************************************************************
* Function Name: SENSOR_PWM_IsEndConversion
********************************************************************************
*
* Summary:
*  Description: Checks for ADC end of conversion for the case one
*  channel and end of scan for the case of multiple channels. It acts
*  as a software version of the EOC. This function provides the
*  programmer with two options. In one mode this function
*  immediately returns with the conversion status. In the other mode,
*  the function does not return (blocking) until the conversion has
*  completed.
*
* Parameters:
*  ADC_RETURN_STATUS        -> Immediately returns conversion result status
*  ADC_WAIT_FOR_RESULT      -> Does not return until ADC complete
*  ADC_RETURN_STATUS_INJ    -> Immediately returns conversion result status
*                              for injection channel
*  ADC_WAIT_FOR_RESULT_INJ  -> Does not return until ADC completes injection
*                              channel conversion
*
* Return:
*  If a non-zero value is returned, the last conversion or scan has completed.
*  If the returned value is zero, the ADC is still in the process of a scan.
*
*******************************************************************************/
uint32 SENSOR_PWM_IsEndConversion(uint32 retMode)
{
    uint32 status = 0u;

    if((retMode & (SENSOR_PWM_RETURN_STATUS | SENSOR_PWM_WAIT_FOR_RESULT)) != 0u)
    {
        do
        {
            status = SENSOR_PWM_SAR_INTR_REG & SENSOR_PWM_EOS_MASK;
        }while((status == 0u) && ((retMode & SENSOR_PWM_WAIT_FOR_RESULT) != 0u));

        if(status != 0u)
        {
            /* Clear EOS bit */
            SENSOR_PWM_SAR_INTR_REG = SENSOR_PWM_EOS_MASK;
        }
    }

    #if(SENSOR_PWM_INJ_CHANNEL_ENABLED)
        if((retMode & (SENSOR_PWM_RETURN_STATUS_INJ | SENSOR_PWM_WAIT_FOR_RESULT_INJ)) != 0u)
        {
            do
            {
                status |= SENSOR_PWM_SAR_INTR_REG & SENSOR_PWM_INJ_EOC_MASK;
            }while(((status & SENSOR_PWM_INJ_EOC_MASK) == 0u) &&
                   ((retMode & SENSOR_PWM_WAIT_FOR_RESULT_INJ) != 0u));

            if((status & SENSOR_PWM_INJ_EOC_MASK) != 0u)
            {
                /* Clear Injection EOS bit */
                SENSOR_PWM_SAR_INTR_REG = SENSOR_PWM_INJ_EOC_MASK;
            }
        }
    #endif /* SENSOR_PWM_INJ_CHANNEL_ENABLED */

    return (status);
}


/*******************************************************************************
* Function Name: SENSOR_PWM_GetResult16
********************************************************************************
*
* Summary:
*  Gets the data available in the SAR DATA register.
*
* Parameters:
*  chan: The ADC channel in which to return the result. The first channel
*  is 0 and the injection channel if enabled is the number of valid channels.
*
* Return:
*  Returns converted data as a signed 16-bit integer
*
*******************************************************************************/
int16 SENSOR_PWM_GetResult16(uint32 chan)
{
    uint32 result;

    /* Halt CPU in debug mode if channel is out of valid range */
    CYASSERT(chan < SENSOR_PWM_TOTAL_CHANNELS_NUM);

    if(chan < SENSOR_PWM_SEQUENCED_CHANNELS_NUM)
    {
        result = CY_GET_REG32((reg32 *)(SENSOR_PWM_SAR_CHAN_RESULT_IND + (uint32)(chan << 2u))) &
                SENSOR_PWM_RESULT_MASK;
    }
    else
    {
        #if(SENSOR_PWM_INJ_CHANNEL_ENABLED)
            result = SENSOR_PWM_SAR_INJ_RESULT_REG & SENSOR_PWM_RESULT_MASK;
        #else
            result = 0u;
        #endif /* SENSOR_PWM_INJ_CHANNEL_ENABLED */
    }

    return ( (int16)result );
}


/*******************************************************************************
* Function Name: SENSOR_PWM_SetChanMask
********************************************************************************
*
* Summary:
*  Sets the channel enable mask.
*
* Parameters:
*  mask: Sets which channels that will be
*  scanned. Setting bits for channels that do not exist will have no
*  effect. For example, if only 6 channels were enabled, setting a
*  mask of 0x0103 would only enable the last two channels (0 and 1).
*  This API will not enable the injection channel.
*  Examples: If the component is setup to sequence through 8
*  channels, a mask of 0x000F would enable channels 0, 1, 2, and 3.
*
* Return:
*  None.
*
*******************************************************************************/
void SENSOR_PWM_SetChanMask(uint32 mask)
{
    SENSOR_PWM_SAR_CHAN_EN_REG = mask & SENSOR_PWM_MAX_CHANNELS_EN_MASK;
}

#if(SENSOR_PWM_INJ_CHANNEL_ENABLED)


    /*******************************************************************************
    * Function Name: SENSOR_PWM_EnableInjection
    ********************************************************************************
    *
    * Summary:
    *  Enables the injection channel for the next scan only.
    *
    * Parameters:
    *  None.
    *
    * Return:
    *  None.
    *
    *******************************************************************************/
    void SENSOR_PWM_EnableInjection(void)
    {
        SENSOR_PWM_SAR_INJ_CHAN_CONFIG_REG |= SENSOR_PWM_INJ_CHAN_EN;
    }

#endif /* SENSOR_PWM_INJ_CHANNEL_ENABLED */


/*******************************************************************************
* Function Name: SENSOR_PWM_SetLowLimit
********************************************************************************
*
* Summary:
*  Sets the low limit parameter for a limit condition.
*
* Parameters:
*  lowLimit: The low limit for a limit condition.
*
* Return:
*  None.
*
*******************************************************************************/
void SENSOR_PWM_SetLowLimit(uint32 lowLimit)
{
    SENSOR_PWM_SAR_RANGE_THRES_REG &= (uint32)(~SENSOR_PWM_RANGE_LOW_MASK);
    SENSOR_PWM_SAR_RANGE_THRES_REG |= lowLimit & SENSOR_PWM_RANGE_LOW_MASK;
}


/*******************************************************************************
* Function Name: SENSOR_PWM_SetHighLimit
********************************************************************************
*
* Summary:
*  Sets the low limit parameter for a limit condition.
*
* Parameters:
*  highLimit: The high limit for a limit condition.
*
* Return:
*  None.
*
*******************************************************************************/
void SENSOR_PWM_SetHighLimit(uint32 highLimit)
{
    SENSOR_PWM_SAR_RANGE_THRES_REG &= (uint32)(~SENSOR_PWM_RANGE_HIGH_MASK);
    SENSOR_PWM_SAR_RANGE_THRES_REG |= (uint32)(highLimit << SENSOR_PWM_RANGE_HIGH_OFFSET);
}


/*******************************************************************************
* Function Name: SENSOR_PWM_SetLimitMask
********************************************************************************
*
* Summary:
*  Sets the channel limit condition mask.
*
* Parameters:
*  mask: Sets which channels that may cause a
*  limit condition interrupt. Setting bits for channels that do not exist
*  will have no effect. For example, if only 6 channels were enabled,
*  setting a mask of 0x0103 would only enable the last two channels (0 and 1).
*
* Return:
*  None.
*
*******************************************************************************/
void SENSOR_PWM_SetLimitMask(uint32 mask)
{
    SENSOR_PWM_SAR_RANGE_INTR_MASK_REG = mask & SENSOR_PWM_MAX_CHANNELS_EN_MASK;
}


/*******************************************************************************
* Function Name: SENSOR_PWM_SetSatMask
********************************************************************************
*
* Summary:
*  Sets the channel saturation event mask.
*
* Parameters:
*  mask: Sets which channels that may cause a
*  saturation event interrupt. Setting bits for channels that do not exist
*  will have no effect. For example, if only 8 channels were enabled,
*  setting a mask of 0x01C0 would only enable two channels (6 and 7).
*
* Return:
*  None.
*
*******************************************************************************/
void SENSOR_PWM_SetSatMask(uint32 mask)
{
    SENSOR_PWM_SAR_SATURATE_INTR_MASK_REG = mask & SENSOR_PWM_MAX_CHANNELS_EN_MASK;
}


/*******************************************************************************
* Function Name: SENSOR_PWM_SetOffset
********************************************************************************
*
* Summary:
*   Description: Sets the ADC offset which is used by the functions
*   ADC_CountsTo_uVolts, ADC_CountsTo_mVolts and ADC_CountsTo_Volts
*   to substract the offset from the given reading
*   before calculating the voltage conversion.
*
* Parameters:
*  chan: ADC channel number.
*  offset: This value is a measured value when the
*          inputs are shorted or connected to the same input voltage.
*
* Return:
*  None.
*
* Global variables:
*  SENSOR_PWM_Offset:  Modified to set the user provided offset.
*
*******************************************************************************/
void SENSOR_PWM_SetOffset(uint32 chan, int16 offset)
{
    /* Halt CPU in debug mode if channel is out of valid range */
    CYASSERT(chan < SENSOR_PWM_TOTAL_CHANNELS_NUM);

    SENSOR_PWM_offset[chan] = offset;
}


/*******************************************************************************
* Function Name: SENSOR_PWM_SetGain
********************************************************************************
*
* Summary:
*  Description: Sets the ADC gain in counts per 10 volt for the voltage
*  conversion functions below. This value is set by default by the
*  reference and input range settings. It should only be used to further
*  calibrate the ADC with a known input or if an external reference is
*  used. Affects the ADC_CountsTo_uVolts, ADC_CountsTo_mVolts
*  and ADC_CountsTo_Volts functions by supplying the correct
*  conversion between ADC counts and voltage.
*
* Parameters:
*  chan: ADC channel number.
*  adcGain: ADC gain in counts per 10 volts.
*
* Return:
*  None.
*
* Global variables:
*  SENSOR_PWM_CountsPer10Volt:  modified to set the ADC gain in counts
*   per 10 volt.
*
*******************************************************************************/
void SENSOR_PWM_SetGain(uint32 chan, int32 adcGain)
{
    /* Halt CPU in debug mode if channel is out of valid range */
    CYASSERT(chan < SENSOR_PWM_TOTAL_CHANNELS_NUM);

    SENSOR_PWM_countsPer10Volt[chan] = adcGain;
}


#if(SENSOR_PWM_DEFAULT_JUSTIFICATION_SEL == SENSOR_PWM__RIGHT)


    /*******************************************************************************
    * Function Name: SENSOR_PWM_CountsTo_mVolts
    ********************************************************************************
    *
    * Summary:
    *  This function converts ADC counts to mVolts
    *  This function is not available when left data format justification selected.
    *
    * Parameters:
    *  chan: The ADC channel number.
    *  adcCounts: Result from the ADC conversion
    *
    * Return:
    *  Results in mVolts
    *
    * Global variables:
    *  SENSOR_PWM_countsPer10Volt:  used to convert ADC counts to mVolts.
    *  SENSOR_PWM_Offset:  Used as the offset while converting ADC counts
    *   to mVolts.
    *
    *******************************************************************************/
    int16 SENSOR_PWM_CountsTo_mVolts(uint32 chan, int16 adcCounts)
    {
        int16 mVolts;

        /* Halt CPU in debug mode if channel is out of valid range */
        CYASSERT(chan < SENSOR_PWM_TOTAL_CHANNELS_NUM);

        /* Divide the adcCount when accumulate averaging mode selected */
        #if(SENSOR_PWM_DEFAULT_AVG_MODE == SENSOR_PWM__ACCUMULATE)
            if((SENSOR_PWM_channelsConfig[chan] & SENSOR_PWM_AVERAGING_EN) != 0u)
            {
                adcCounts /= SENSOR_PWM_DEFAULT_AVG_SAMPLES_DIV;
            }
        #endif /* SENSOR_PWM_DEFAULT_AVG_MODE == SENSOR_PWM__ACCUMULATE */

        /* Subtract ADC offset */
        adcCounts -= SENSOR_PWM_offset[chan];

        mVolts = (int16)((((int32)adcCounts * SENSOR_PWM_10MV_COUNTS) + ( (adcCounts > 0) ?
                 (SENSOR_PWM_countsPer10Volt[chan] / 2) : (-(SENSOR_PWM_countsPer10Volt[chan] / 2)) ))
                 / SENSOR_PWM_countsPer10Volt[chan]);

        return( mVolts );
    }


    /*******************************************************************************
    * Function Name: SENSOR_PWM_CountsTo_uVolts
    ********************************************************************************
    *
    * Summary:
    *  This function converts ADC counts to micro Volts
    *  This function is not available when left data format justification selected.
    *
    * Parameters:
    *  chan: The ADC channel number.
    *  adcCounts: Result from the ADC conversion
    *
    * Return:
    *  Results in uVolts
    *
    * Global variables:
    *  SENSOR_PWM_countsPer10Volt:  used to convert ADC counts to uVolts.
    *  SENSOR_PWM_Offset:  Used as the offset while converting ADC counts
    *   to mVolts.
    *
    * Theory:
    *  Care must be taken to not exceed the maximum value for a 31 bit signed
    *  number in the conversion to uVolts and at the same time not loose
    *  resolution.
    *  To convert adcCounts to microVolts it is required to be multiplied
    *  on 10 million and later divide on gain in counts per 10V.
    *
    *******************************************************************************/
    int32 SENSOR_PWM_CountsTo_uVolts(uint32 chan, int16 adcCounts)
    {
        int64 uVolts;

        /* Halt CPU in debug mode if channel is out of valid range */
        CYASSERT(chan < SENSOR_PWM_TOTAL_CHANNELS_NUM);

        /* Divide the adcCount when accumulate averaging mode selected */
        #if(SENSOR_PWM_DEFAULT_AVG_MODE == SENSOR_PWM__ACCUMULATE)
            if((SENSOR_PWM_channelsConfig[chan] & SENSOR_PWM_AVERAGING_EN) != 0u)
            {
                adcCounts /= SENSOR_PWM_DEFAULT_AVG_SAMPLES_DIV;
            }
        #endif /* SENSOR_PWM_DEFAULT_AVG_MODE == SENSOR_PWM__ACCUMULATE */

        /* Subtract ADC offset */
        adcCounts -= SENSOR_PWM_offset[chan];

        uVolts = ((int64)adcCounts * SENSOR_PWM_10UV_COUNTS) / SENSOR_PWM_countsPer10Volt[chan];

        return( (int32)uVolts );
    }


    /*******************************************************************************
    * Function Name: SENSOR_PWM_CountsTo_Volts
    ********************************************************************************
    *
    * Summary:
    *  Converts the ADC output to Volts as a floating point number.
    *  This function is not available when left data format justification selected.
    *
    * Parameters:
    *  chan: The ADC channel number.
    *  Result from the ADC conversion
    *
    * Return:
    *  Results in Volts
    *
    * Global variables:
    *  SENSOR_PWM_countsPer10Volt:  used to convert ADC counts to Volts.
    *  SENSOR_PWM_Offset:  Used as the offset while converting ADC counts
    *   to mVolts.
    *
    *******************************************************************************/
    float32 SENSOR_PWM_CountsTo_Volts(uint32 chan, int16 adcCounts)
    {
        float32 volts;

        /* Halt CPU in debug mode if channel is out of valid range */
        CYASSERT(chan < SENSOR_PWM_TOTAL_CHANNELS_NUM);

        /* Divide the adcCount when accumulate averaging mode selected */
        #if(SENSOR_PWM_DEFAULT_AVG_MODE == SENSOR_PWM__ACCUMULATE)
            if((SENSOR_PWM_channelsConfig[chan] & SENSOR_PWM_AVERAGING_EN) != 0u)
            {
                adcCounts /= SENSOR_PWM_DEFAULT_AVG_SAMPLES_DIV;
            }
        #endif /* SENSOR_PWM_DEFAULT_AVG_MODE == SENSOR_PWM__ACCUMULATE */

        /* Subtract ADC offset */
        adcCounts -= SENSOR_PWM_offset[chan];

        volts = ((float32)adcCounts * SENSOR_PWM_10V_COUNTS) / (float32)SENSOR_PWM_countsPer10Volt[chan];

        return( volts );
    }

#endif /* End SENSOR_PWM_DEFAULT_JUSTIFICATION_SEL == SENSOR_PWM__RIGHT */


/* [] END OF FILE */
