# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Henry Alberto\Desktop\CAN_ROBOT\Test_CAN_Module_3.cydsn\Test_CAN_Module_3.cyprj
# Date: Wed, 01 Feb 2017 01:47:26 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFCLK} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\Henry Alberto\Desktop\CAN_ROBOT\Test_CAN_Module_3.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Henry Alberto\Desktop\CAN_ROBOT\Test_CAN_Module_3.cydsn\Test_CAN_Module_3.cyprj
# Date: Wed, 01 Feb 2017 01:47:21 GMT
