/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SENSOR_U.h"
#include "Timer_1.h"
#include "Timer.h"
#include "Clock_1.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "Int_Serial.h"
#include "RX_2.h"
#include "RX_2_aliases.h"
#include "TX_2.h"
#include "TX_2_aliases.h"
#include "CAN.h"
#include "SENSOR_U_IntClock.h"
#include "CAN_isr.h"
#include "CAN_HFCLK.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

